/*
 * This file is automatically generated by `ruby gen-sigconf.rb`.
 * All direct changes to this file will be lost.
 */

#ifndef MRUBY_SIGNATURE_CONFIG_H
#define MRUBY_SIGNATURE_CONFIG_H 1

#include <mruby.h> /* for mrbconf.h */
#include <mruby/version.h>
#include <stdint.h>

#if MRUBY_RELEASE_NO < 20000
# if !defined(MRB_INT16) && !defined(MRB_INT32) && !defined(MRB_INT64)
#  define MRB_INT32 1
# endif
#endif

#if MRUBY_RELEASE_NO < 30000
# if defined(MRB_WITHOUT_FLOAT)
#  define MRB_NO_FLOAT 1
# endif

# if defined(MRB_USE_FLOAT)
#  define MRB_USE_FLOAT32 1
# endif

# if defined(MRB_METHOD_CACHE)
#  undef MRB_NO_METHOD_CACHE
# else
#  define MRB_NO_METHOD_CACHE 1
# endif

# if defined(MRB_METHOD_T_STRUCT)
#  define MRB_USE_METHOD_T_STRUCT 1
# endif

# if defined(MRB_ENABLE_DEBUG_HOOK)
#  define MRB_USE_DEBUG_HOOK 1
# endif

# if defined(MRB_ENABLE_ALL_SYMBOLS)
#  define MRB_USE_ALL_SYMBOLS 1
# endif

# if defined(MRB_ENABLE_CXX_ABI)
#  define MRB_USE_CXX_ABI 1
# elif defined(MRB_ENABLE_CXX_EXCEPTION)
#  define MRB_USE_CXX_EXCEPTION 1
# endif
#endif /* MRUBY_RELEASE_NO < 30000 */

#if defined(MRB_INT32)
# define MRBSIG_WORDSIZE UINT32_C(0x20bd8ede)
#elif defined(MRB_INT64)
# define MRBSIG_WORDSIZE UINT32_C(0x417b1dbc)
#else
# error "wrong conditional"
#endif

#if defined(MRB_NAN_BOXING)
# define MRBSIG_BOXING_TYPE UINT32_C(0x13a29877)
#elif defined(MRB_WORD_BOXING)
# define MRBSIG_BOXING_TYPE UINT32_C(0x274530ee)
#else
# define MRBSIG_BOXING_TYPE UINT32_C(0x00000000)
#endif

#if defined(MRB_NO_FLOAT)
# define MRBSIG_FLOAT_TYPE UINT32_C(0xa541927e)
#elif defined(MRB_USE_FLOAT32)
# define MRBSIG_FLOAT_TYPE UINT32_C(0x4f6f520d)
#else
# define MRBSIG_FLOAT_TYPE UINT32_C(0x00000000)
#endif

#if defined(MRB_USE_METHOD_T_STRUCT)
# define MRBSIG_METHOD_CONTAINER UINT32_C(0xdd45aab8)
#else
# define MRBSIG_METHOD_CONTAINER UINT32_C(0x00000000)
#endif

#if defined(MRB_ENDIAN_BIG)
# define MRBSIG_ENDIAN UINT32_C(0x38116fac)
#else
# define MRBSIG_ENDIAN UINT32_C(0x00000000)
#endif

#if defined(MRB_USE_DEBUG_HOOK)
# define MRBSIG_DEBUG_HOOK UINT32_C(0xef306b19)
#else
# define MRBSIG_DEBUG_HOOK UINT32_C(0x00000000)
#endif

#if defined(MRB_USE_ALL_SYMBOLS)
# define MRBSIG_ALL_SYMBOLS UINT32_C(0x68032cc8)
#else
# define MRBSIG_ALL_SYMBOLS UINT32_C(0x00000000)
#endif

#if defined(MRB_NO_METHOD_CACHE)
# define MRBSIG_METHOD_CACHE UINT32_C(0x493c7d27)
#else
# define MRBSIG_METHOD_CACHE UINT32_C(0x00000000)
#endif

#if defined(MRB_BYTECODE_DECODE_OPTION)
# define MRBSIG_DECODE_OPTION UINT32_C(0xf43ed648)
#else
# define MRBSIG_DECODE_OPTION UINT32_C(0x00000000)
#endif

#if defined(MRB_GC_FIXED_ARENA)
# define MRBSIG_GC_FIXED_ARENA UINT32_C(0xcb567ba5)
#else
# define MRBSIG_GC_FIXED_ARENA UINT32_C(0x00000000)
#endif

#if defined(MRB_FIXED_STATE_ATEXIT_STACK)
# define MRBSIG_FIXED_ATEXIT UINT32_C(0x9771f7c1)
#else
# define MRBSIG_FIXED_ATEXIT UINT32_C(0x00000000)
#endif

#if defined(MRB_USE_CXX_ABI)
# define MRBSIG_CXX_HANDLING UINT32_C(0x3171d430)
#elif defined(MRB_USE_CXX_EXCEPTION)
# define MRBSIG_CXX_HANDLING UINT32_C(0x62e3a860)
#else
# define MRBSIG_CXX_HANDLING UINT32_C(0x00000000)
#endif

#define MRBSIG_INITIAL  UINT32_C(0xd49f4aa2)
#define MRBSIG_XOROUT   UINT32_C(0xffffffff)

#define MRUBY_SIGNATURE (MRBSIG_INITIAL ^ \
                         MRBSIG_WORDSIZE ^ \
                         MRBSIG_BOXING_TYPE ^ \
                         MRBSIG_FLOAT_TYPE ^ \
                         MRBSIG_METHOD_CONTAINER ^ \
                         MRBSIG_ENDIAN ^ \
                         MRBSIG_DEBUG_HOOK ^ \
                         MRBSIG_ALL_SYMBOLS ^ \
                         MRBSIG_METHOD_CACHE ^ \
                         MRBSIG_DECODE_OPTION ^ \
                         MRBSIG_GC_FIXED_ARENA ^ \
                         MRBSIG_FIXED_ATEXIT ^ \
                         MRBSIG_CXX_HANDLING ^ \
                         MRBSIG_XOROUT)

int mruby_signature_check_internal(mrb_state *mrb, uint32_t ver, uint32_t sig);

#endif /* MRUBY_SIGNATURE_CONFIG_H */
